version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules

  api:
    build: ./backend
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./contracts:/app/contracts:ro
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_NAME=gdash_weather
      - RABBITMQ_URL=amqp://rabbitmq:5672

  collector:
    build: ./collector-python
    container_name: collector
    depends_on:
      - rabbitmq
    volumes:
      - ./collector-python:/app
      - ./contracts:/app/contracts:ro
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - LATITUDE=${LATITUDE}
      - LONGITUDE=${LONGITUDE}

  worker:
    build: ./worker-go
    container_name: worker
    depends_on:
      - rabbitmq
      - api
    volumes:
      - ./contracts:/app/contracts:ro
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - API_URL=http://api:3000

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672" # painel
      - "5672:5672" # AMQP
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}
    volumes:
      - ./infra/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
